{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "vault-configurator" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vault-configurator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
