apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2025-07-08T01:34:16Z"
    operators.operatorframework.io/builder: operator-sdk-v1.40.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: vault-configurator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Configure SecretEngines, Policies, and AuthMethods declaratively
  displayName: vault-configurator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - helm
  - vault
  links:
  - name: Vault Configurator
    url: https://vault-configurator.domain
  maturity: alpha
  provider:
    name: apexdriver
  version: 0.0.1
