# This rule is not used by the project vault-configurator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to vault.apexdriver.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vault-configurator
    app.kubernetes.io/managed-by: kustomize
  name: secretenginemount-viewer-role
rules:
- apiGroups:
  - vault.apexdriver.dev
  resources:
  - secretenginemounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vault.apexdriver.dev
  resources:
  - secretenginemounts/status
  verbs:
  - get
