apiVersion: vault.apexdriver.dev/v1alpha1
kind: VaultSecret
metadata:
  labels:
    app.kubernetes.io/name: vault-configurator
    app.kubernetes.io/managed-by: kustomize
  name: vaultsecret-sample
spec:
  mounts:
    - mount: secret-v1
      secrets:
        - path: aws/iam
          data:
            AWS_ACCESS_KEY_ID: changeme
            AWS_SECRET_ACCESS_KEY: changeme
    - mount: secret-v2
      secrets:
        - path: aws/iam
          data:
            AWS_ACCESS_KEY_ID: changeme
            AWS_SECRET_ACCESS_KEY: changme
