apiVersion: vault.apexdriver.dev/v1alpha1
kind: SecretEngineMount
metadata:
  labels:
    app.kubernetes.io/name: vault-configurator
    app.kubernetes.io/managed-by: kustomize
  name: secretenginemount-sample
spec:
  mounts:
    - type: kv
      path: secret-v1
      options:
        version: "1"
    - type: kv
      path: secret-v2
      options:
        version: "2"
