name: Generate Manifests

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'internal/**'

permissions:
  contents: write

env:
  GO_VERSION: '1.24'

jobs:
  generate-manifests:
    name: Generate Kubernetes manifests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Generate manifests
        run: make generate

      - name: Make manifests
        run: make manifests

      - name: Copy CRDs to Helm chart
        run: cp config/crd/bases/* charts/vault-configurator/templates/crds/

      - name: Commit and push manifests if changed
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add config/crd/bases/ charts/vault-configurator/templates/crds/
          if git diff --cached --quiet; then
            echo "No manifest changes"
          else
            git commit -m "chore: generate manifests"
            git push
          fi